//
//  StoryViewController.m
//  Pictaphone
//
//  Created by Kelly Hutchison on 11/22/14.
//  Copyright (c) 2014 Kelly Hutchison. All rights reserved.
//

#import "StoryViewController.h"
#import "MainViewController.h"
#import "model.h"

#define iPhoneYCoordinateOffset 5.0
#define iPadYCoordinateOffset 7.0

@interface StoryViewController ()
@property (nonatomic,strong) model *model;
- (IBAction)startOverPressed:(id)sender;

@property (weak, nonatomic) IBOutlet UIScrollView *scrollViewOutlet;
@property (weak, nonatomic) IBOutlet UIImageView *currentImage;
@property (weak, nonatomic) IBOutlet UITextView *currentPhrase;
@property (weak, nonatomic) IBOutlet UIPageControl *pageControl;

@property (nonatomic,assign) NSInteger postItNoteYOffset;
@property (nonatomic,assign) BOOL autoGenerateSwitchOn;
@property (nonatomic,assign) BOOL autoGeneratedFirstRound;

@end

@implementation StoryViewController

- (id)initWithCoder:(NSCoder *)aDecoder
{
    self = [super initWithCoder:aDecoder];
    if (self) {
        // Custom initialization
        _model = [model sharedInstance];
    }
    return self;
}

- (void)viewDidLoad
{
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    self.view.opaque = YES;
    self.view.backgroundColor = [UIColor whiteColor];
    
    [self.navigationController setNavigationBarHidden:YES animated:NO];
    
    self.autoGeneratedFirstRound = [self.model isFirstRoundAutoGenerated];
    self.autoGenerateSwitchOn = self.autoGeneratedFirstRound;
    
    [self initializeScrollView];
    [self loadScrollViewPages];
    
    self.currentImage.hidden = YES;
    self.currentPhrase.hidden = YES;
    
    self.postItNoteYOffset = self.scrollViewOutlet.frame.origin.y;
}

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

- (void)initializeScrollView
{
    self.scrollViewOutlet.delegate = self;
    self.scrollViewOutlet.userInteractionEnabled = YES;
    self.scrollViewOutlet.pagingEnabled = YES;
    
    NSInteger pageCount = [self.model turnsCompleted];
    
    if(self.autoGeneratedFirstRound)
    {
        pageCount++;
    }
    
    CGSize contentSize = CGSizeMake(self.view.bounds.size.width * pageCount, self.currentImage.frame.size.height);
    self.scrollViewOutlet.contentSize =  contentSize;
    
    self.pageControl.numberOfPages = pageCount;
    self.pageControl.currentPageIndicatorTintColor = [UIColor greenColor];
}

- (void)loadPostItNoteImages:(int) pageNumber
{
    UIImage *image = [UIImage imageNamed:@"post_it_two.png"];
    UIImageView *postItNote = [[UIImageView alloc] initWithImage:image];
    
    CGRect frame = self.scrollViewOutlet.frame;
    frame.origin = CGPointMake((self.view.bounds.size.width * pageNumber), self.postItNoteYOffset);
    
    postItNote.frame = frame;
    postItNote.contentMode = UIViewContentModeScaleAspectFit;
    postItNote.hidden = NO;
    
    [self.scrollViewOutlet addSubview:postItNote];
}

- (void)loadScrollViewPages
{
    NSInteger contentCount;
    if(self.autoGeneratedFirstRound)
    {
        contentCount = [self.model contentsArrayCount] + 1;
    }
    else {
        contentCount = [self.model contentsArrayCount];
    }
    for(int i=0; i < contentCount; i++)
    {
        [self loadPostItNoteImages:i];
        
        // Determine font size of labels based on device
        float yCoordinateOffset;
        
        if(UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPhone) {
            yCoordinateOffset = iPhoneYCoordinateOffset;
        } else {
            yCoordinateOffset = iPadYCoordinateOffset;
        }
        
        id object;
        if(self.autoGenerateSwitchOn) {
           if([self.model isSetRandomImage]) {
               object = [self.model valueOfRandomImage];
           } else if([self.model isSetRandomPhrase]) {
               object = [self.model valueOfRandomPhrase];
           }
            self.autoGenerateSwitchOn = NO;
        } else {
            if(self.autoGeneratedFirstRound) {
                object = [self.model valueOfContentsArrayAtIndex:i-1];
            } else {
                object = [self.model valueOfContentsArrayAtIndex:i];
            }
        }
        
        // PHRASE
        if([object isKindOfClass:[NSString class]])
        {
            [self addTextViewToScrollViewOnPage:i forObject:object withOffset:yCoordinateOffset];
        }
        // IMAGE
        else if([object isKindOfClass:[UIImage class]])
        {
            [self addImageViewToScrollViewOnPage:i forObject:object withOffset:yCoordinateOffset];
        }
    }
}

-(void)addImageViewToScrollViewOnPage:(NSInteger)page forObject:(id)object withOffset:(CGFloat) yCoordinateOffset
{
    UIImageView *imageToDisplay = [[UIImageView alloc] initWithImage:(UIImage*)object];
    imageToDisplay.frame = CGRectMake(self.scrollViewOutlet.frame.size.width * page, self.scrollViewOutlet.bounds.origin.y + yCoordinateOffset, self.currentImage.frame.size.width, self.currentImage.frame.size.height);
    imageToDisplay.userInteractionEnabled = NO;
    imageToDisplay.contentMode = UIViewContentModeScaleAspectFit;
    imageToDisplay.backgroundColor = [UIColor clearColor];
    [self.scrollViewOutlet addSubview:imageToDisplay];
}

-(void)addTextViewToScrollViewOnPage:(NSInteger)page forObject:(id)object withOffset:(CGFloat) yCoordinateOffset
{
    NSString *phrase = (NSString*)object;
    
    UITextView *phraseToDisplay = [[UITextView alloc] init];
    phraseToDisplay.frame = CGRectMake(self.scrollViewOutlet.frame.size.width * page, self.scrollViewOutlet.bounds.origin.y + yCoordinateOffset, self.currentPhrase.frame.size.width, self.currentPhrase.frame.size.height);
    
    phraseToDisplay.text = phrase;
    phraseToDisplay.backgroundColor = [UIColor clearColor];
    phraseToDisplay.userInteractionEnabled = NO;
    phraseToDisplay.scrollEnabled = YES;
    phraseToDisplay.editable = NO;
    phraseToDisplay.font = [UIFont fontWithName:@"Tamil Sangam MN" size:28.0];
    phraseToDisplay.textAlignment = NSTextAlignmentCenter;
    
    [self.scrollViewOutlet addSubview:phraseToDisplay];
}

/*
#pragma mark - Navigation

// In a storyboard-based application, you will often want to do a little preparation before navigation
- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender
{
    // Get the new view controller using [segue destinationViewController].
    // Pass the selected object to the new view controller.
}
*/

- (IBAction)startOverPressed:(id)sender {
     // reset random var model objs
    [self.model setRandomImageStatus:NO];
    [self.model setRandomPhraseStatus:NO];
    
    [self.navigationController popToRootViewControllerAnimated:YES];
}

- (void) scrollViewDidScroll:(UIScrollView *)scrollView
{
    // Get the current instruction page number
    NSInteger currentPage = self.scrollViewOutlet.contentOffset.x / self.scrollViewOutlet.frame.size.width;
    
    // Set the page control to reflect the current page
    self.pageControl.currentPage = currentPage;
}

@end
